### ISSUE TITLE
Make web links clickable

### ISSUE THREAD

**Issue by robert-virkus** [open-xchange/ox-coi#247]
**Is your feature request related to a problem? Please describe.**
When I receive or send a web link, I cannot open the link, I can only copy the whole message.

**Describe the solution you'd like**
I want to be able to click/tap on the link to open it.

[Internal bug tracker](https://jira.open-xchange.com/browse/OT-494)

**Comment by Boehrsi** [comment]
Requires message content splitting. See [internal bug tracker](https://jira.open-xchange.com/browse/OT-515).

**Comment by phranck** [comment]
@Boehrsi My thoughts: Since this is a completely different ticket than [mentions](https://github.com/open-xchange/ox-coi/issues/124) and [simple markups](https://github.com/open-xchange/ox-coi/issues/248) I ask myself if we should do this all at once in one single step, or if we should do clickable links first and very pragmatic (so we could use a very small plugin called [link_text](https://github.com/aleksanderwozniak/link_text/blob/master/lib/link_text.dart)) beforehand?

What do you think?

**Comment by Boehrsi** [comment]
First sorry for overlooking this comment... getting way to much Github notifications right now :D

A good question, in general we should try to aim for a solution that brings us closer to a complete implementation of all tickets at once. I'm not sure in regards to used plugins and stuff like that but I think our solution should look once at the text or the text parts and apply all "special actions". I would like to avoid going over everything for links, again for formatting and again for mentions etc..
The message splitting is now there (in a simple but working way), so we can continue doing the whole stuff.
I'm, thinking about something like this:

- Check if formatting, mentions, links of any kind or something else is within a text (already added first checking methods in the message splitting ticket)
- If not just display the text
- If something is in there split the text
- Check every token if formatting / linking or what so ever should be applied and apply if necessary
