### ISSUE TITLE
Message state is not always updated

### ISSUE THREAD

**Issue by matthesatox** [open-xchange/ox-coi#507]
**Describe the bug**

E.g. forwarded videos won't be marked as sent in chat history. Only killing app and restart refreshes the view. Same could also happen for normal text messages. Sometimes it's enough to leave the view and reopen the chat.

**To Reproduce**

Occurrence: sometimes
1. Go to a chat which contains a video
2. Long tab on video in chat history
3. Select "Forward"
4. Select a recipient (E-Mail recipient in that case)
5. Send the video
6. Don't close the chat view

**Actual result**

The forwarded video has already arrived in email account and the sand clock doesn't change to checkmark. Only killing the app and reopen it refresh the view.

**App information (please complete the following information):**
 - App version: 0.600.1 (514)
 - Plugin version:
 - Delta Chat Core version: 
 - Flutter version: 

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4 final

**Additional context**

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-787). 

_Updated by developer._

**Comment by Boehrsi** [comment]
Notes:

- Reduce `MessagesListBloc` count
- Use `BlocProvider.of()` instead of unnecessary passing of BloCs
- ChatBloc listens globally to update events for messages and relays + replays those to interested parties. MessageItemBlocs aren't listening to message state updates anymore. This leads to less listeners, reliable event handling (late registration within the MessageItemBloc lead to not handled events, resulting in missing states) and a less error prone approach in general
- Pass chatBloc to MessageItemBloc via constructor

**Comment by Boehrsi** [comment]
Additional:

- chart.dart buildRow() => ChatAppBar widget

**Comment by Boehrsi** [comment]
Fixes:

- State not updated (sending, sent, read)
- Flickering due to numerous loading cycles or multiple listeners
- Wrong long press menu is shown for failed or attachment messages
- View not updated if a new / freshly sent message fails instantly
- Broken state for messages, which are sent directly after a failed message
- UI error (shortly shown red screen) on deleting a message
- Possibly also fixes #506
